name = "radar-advanta"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[vars]
BACKEND_URL = "https://ais-pre-5a6afjgobl6oxlzhzq46nb-961275344911.asia-southeast1.run.app"
